version: "3.5"

volumes:
  postgres-data-1:
  redis-data-1:
  spring-node-b-data:

services:

  # =================== Backend ===================
  postgres-1:
    image: postgres
    env_file:
      - ./envs/node-1/postgres.env
    volumes:
      - postgres-data-1:/var/lib/postgresql/data

  redis-1:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data-1:/data
    restart: always

  keycloak-1:
    image: jboss/keycloak
    env_file:
      - ./envs/node-1/keycloak.env
      - ./envs/node-1/postgres.env
    depends_on:
      - postgres-1
    ports:
      - 8081:8080

  backend-1:
    build:
      context: "./backend"
    command:
      - make
      - dev
    env_file:
      - ./envs/node-1/backend.env
      - ./envs/node-1/postgres.env
    ports:
      - 3001:3000
    volumes:
      - /opt/node_modules
      - ./backend:/opt

  react-1:
    build:
      context: ./react
    command: ["npm", "start"]
    ports:
      - "4001:3000"
    volumes:
      - /app/node_modules
      - ./react:/app

  mailhog-1:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    ports:
      - "1026:1025"
      - "8026:8025"
    entrypoint: ["/bin/sh", "-c", "MailHog &>/dev/null"]

  swagger-1:
    build:
      context: ./swagger-api/
    ports:
      - '8889:8080'
    volumes:
      - ./swagger-api/swagger:/swagger-api:delegated

  # ========================= xx ==========================

  #=========================Corda==========================
  corda-node-1:
    ports:
      - "10007:10007"
      - "10008:10008"
      - "10009:10009"
      - "2225:2225"
    image: corda/corda-zulu-java1.8-4.3:latest
    container_name: partyb
    volumes:
      - ./corda/build/nodes/PartyB/node.conf:/etc/corda/node.conf
      - ./corda/build/nodes/PartyB/cordapps/:/opt/corda/cordapps/
      - ./corda/build/nodes/PartyB/certificates/:/opt/corda/certificates/
      - ./corda/build/nodes/PartyB/network-parameters:/opt/corda/network-parameters
      - ./corda/build/nodes/PartyB/additional-node-infos/:/opt/corda/additional-node-infos/
      - ./corda/build/nodes/PartyB/logs/:/opt/corda/logs/

  spring-node-1:
    ports:
      - "8433:8433"
    container_name: spring-node-b
    depends_on:
      - corda-node-1
    restart: always
    build:
      context: corda/clients
      dockerfile: Dockerfile
    image: spring-boot-docker:v1.1
    env_file:
      - ./envs/node-1/corda.env
    command: sh -c "sh entrypoint.sh"
    volumes:
      - spring-node-b-data:/tmp

    #========================= xx ======================

networks:
  default:
    external:
      name: deqode
