FROM node:12-alpine

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL

WORKDIR /app
COPY . /app
RUN ["npm", "install"]
RUN [ "npm", "i", "-g", "serve"]
RUN [ "npm", "run", "build"]
