const STATUS_ENUM = {
  'ACTIVE': 'active',
  'INACTIVE': 'inactive',
  'DELETED': 'deleted'
}

const USER_TYPE_ENUM = {
  'SERVICE_ACCOUNT': 'SERVICE',
  'USER_ACCOUNT': 'USER',
  'ADMIN_ACCOUNT': 'ADMIN'
}

const DOCUMENT_PERMISSIONS_ENUM = {
  'VIEW': 'VIEW',
  'EDIT': 'EDIT'
}

const DOCUMENT_ACCESS_SCOPE_ENUM = {
  'USER': 'USER',
  'ORGANIZATION': 'ORGANIZATION',
  'NETWORK': 'NETWORK'
}

export { STATUS_ENUM, USER_TYPE_ENUM, DOCUMENT_PERMISSIONS_ENUM, DOCUMENT_ACCESS_SCOPE_ENUM }
